name: 1B. Between Delay

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["1A. Unified Stream"]
  #   types:
  #     - completed

jobs:
  run-script:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Execute Python Script
      run: python between_delay.py